POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Testing user ID",
  "author": "Matti Luukkainen",
  "url": "https://mluukkai.fi",
  "likes": 0,
  "userId": "5f23aec3358cd72a6cc88ba6"
}