POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9udnNkYXRhIiwiaWQiOiI1ZjIzZDllOGU4YzNkMjI5NWMxMmUyZTgiLCJpYXQiOjE1OTYxODY4NTV9.e9PitAu5916tbkJOTedbCDZrBL1n4xk-Q8As9zYcuo0

{
  "title": "Anton's awesome post",
  "author": "Anton Klåvus",
  "url": "https://anton.fi"
}
